services:
  allergy-track:
    build: .
    image: allergy-track:latest
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
    # No need for absolute paths or complex commands here,
    # as the Dockerfile handles the structure and entrypoint.
