services:
  allergy-track:
    build:
      context: .
      args:
        BUILD_DATE: ${BUILD_DATE:-unknown}
        GIT_HASH: ${GIT_HASH:-unknown}
    image: allergy-track:latest
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/srv/pb_data
    # No need for absolute paths or complex commands here,
    # as the Dockerfile handles the structure and entrypoint.

volumes:
  pb_data:
