version: "3"

vars:
  SUDO: 'sudo' # Modifiez en '' si vous ne voulez pas utiliser sudo par défaut


tasks:
  install:
    desc: Installe les dépendances du projet (Frontend + Login AWS)
    cmds:
      - cd frontend && npm ci

  build:
    desc: Build de l'application Angular
    cmds:
      - cd frontend && npm run build

  start:
    desc: Démarre l'application via Docker Compose
    cmds:
      - "{{.SUDO}} docker compose up -d"

  stop:
    desc: Arrête l'application
    cmds:
      - "{{.SUDO}} docker compose down"

  restart:
    desc: Redémarre l'application (utile après un build)
    cmds:
      - task: stop
      - task: start

  status:
    desc: Affiche l'état des services
    cmds:
      - "{{.SUDO}} docker compose ps"

  build-and-start:
    desc: Construit l'image Docker et redémarre l'application
    cmds:
      - "{{.SUDO}} docker compose up -d --build"

  upsert-admin:
    desc: Crée ou met à jour un utilisateur administrateur (Docker)
    cmds:
      - "{{.SUDO}} docker compose exec allergy-track /usr/local/bin/pocketbase superuser upsert {{.EMAIL}} {{.PASS}} --dir=/srv/pb_data"
    vars:
      EMAIL: 'admin@allergy-track.local'
      PASS: 'admin123456'

  reset-db:
    desc: Réinitialise la base de données Pocketbase en supprimant son dossier de données local (./var/pb_data)
    cmds:
      - task: stop
      - "{{.SUDO}} docker run --rm -v $(pwd)/var/pb_data:/srv/pb_data alpine sh -c \"rm -rf /srv/pb_data/* /srv/pb_data/.[!.]* ; chmod 777 /srv/pb_data\""
      - task: start

  test-docker:
    desc: Construit et teste l'image Docker localement
    cmds:
      - "{{.SUDO}} docker compose build"
      - "{{.SUDO}} docker compose up -d"
      - "echo 'Waiting for PocketBase to start...'"
      - sleep 5
      - curl -f http://localhost:8090/ || ({{.SUDO}} docker compose logs && exit 1)
      - "echo '✅ Test Docker réussi !'"
      - "{{.SUDO}} docker compose down"

  update:
    desc: Met à jour l'application (git pull + rebuild Docker) sur le Synology
    cmds:
      - git pull
      - "{{.SUDO}} docker compose up -d --build"
